---
download:
    mars_url: https://nightlies.tbb.torproject.org/nightly-updates
build_targets:
    linux-aarch64: Linux_aarch64-gcc3
    linux-x86_64: Linux_x86_64-gcc3
    windows-i686:
        - WINNT_x86-gcc3
        - WINNT_x86-gcc3-x86
        - WINNT_x86-gcc3-x64
    windows-x86_64: WINNT_x86_64-gcc3-x64
    macos:
      - Darwin_x86_64-gcc3
      - Darwin_aarch64-gcc3
channels:
    nightly: nightly_version
versions:
    nightly_version:
        platformVersion: 115.1.0
        detailsURL: https://nightlies.tbb.torproject.org/
        # minSupportedOsVersion on macOS corresponds to the Darwin version ( https://en.wikipedia.org/wiki/Darwin_(operating_system) )
        macos:
            # macOS v10.15.0
            minSupportedOSVersion: 19.0.0
        # minSupportedOsVersion on Windows corresponds to the operating system version ( https://docs.microsoft.com/en-us/windows/win32/sysinfo/operating-system-version )
        windows-i686:
            # Windows 10
            minSupportedOSVersion: 10.0
        windows-x86_64:
            # Windows v10
            minSupportedOSVersion: 10.0
        linux-x86_64:
            minSupportedInstructionSet: SSE2
mar_compression: xz
